on:
  push:
    branches:
      - design-tokens
    paths:
      - "tokens/tokens.json"

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create pull request
        run: |
          npm install token-transformer
          npx token-transformer tokens/tokens.json tokens/tokens-transformed.json
          node scripts/build.js
          git config user.name "shanpig"
          git config user.email "shanpigLiao@gmail.com"
          git add .
          git commit -m'transform and build tokens'
          git push https://${{ secrets.GH_PAT }}@github.com/shanpig/test.git HEAD:design-tokens
          gh pr create -B main -H design-tokens --title 'Design tokens update' --body 'Created by Github action'