on:
  push:
    branches:
      - design-tokens
    paths:
      - "tokens/tokens.json"

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "set git config"
          git config user.name "shanpig"
          git config user.email "shanpigLiao@gmail.com"
          
          echo "fetch origin main"
          git fetch origin main
          echo "checkout design-tokens"
          git checkout design-tokens
          echo "rebase origin main"
          git rebase origin/main
          
          echo "install token-transformer"
          npm install token-transformer
          echo "transform tokens"
          npx token-transformer tokens/tokens.json tokens/tokens-transformed.json
          echo "build tokens"
          node ./scripts/build.js

          echo "commit changes and create pr"
          git add .
          git commit -m'transform and build tokens'
          git push origin design-tokens
          gh pr create -B main -H design-tokens --title 'Design tokens update' --body 'Created by Github action'