on:
  push:
    branches:
      - design-tokens

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your scripts
        run: |
          # Your custom scripts go here
          # Modify your project as needed
          echo "hello testing"

      # - name: Commit changes
      #   run: |
      #     git config user.name "Your Name"
      #     git config user.email "your.email@example.com"
      #     git add .
      #     git commit -m "Auto-commit by GitHub Actions"
      #     git push https://${{ secrets.GH_PAT }}@github.com/your-username/your-repo.git HEAD:your-branch-name
